export default [
   {  
      id: 1,
      name: 'Rick Sanchez',
      cla: "rick",
      status: 'Alive',
      species: 'Human',
      gender: 'Male',
      origin: {
         name: 'Earth (C-137)',
         url: '',
      },
      image: "/static/media/rickand-morty-rick.b8410115f416c5fd004a.png",
   },
   {
      id: 2,
      cla: "morty",
      name: 'Morty Smith',
      status: 'Alive',
      species: 'Human',
      gender: 'Male',
      origin: {
         name: 'unknown',
         url: '',
      },
      image: "/static/media/morty.6e5eea7318799714c4ad.png",
   },
   {
      id: 3,
      cla: "summer",
      name: 'Summer Smith',
      status: 'Alive',
      species: 'Human',
      gender: 'Female',
      origin: {
         name: 'Earth (Replacement Dimension)',
         url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
   },
   {
      id: 4,
      cla: "beth",
      name: 'Beth Smith',
      status: 'Alive',
      species: 'Human',
      gender: 'Female',
      origin: {
         name: 'Earth (Replacement Dimension)',
         url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
   },
   {
      id: 5,
      cla: "jerry",
      name: 'Jerry Smith',
      status: 'Alive',
      species: 'Human',
      gender: 'Male',
      origin: {
         name: 'Earth (Replacement Dimension)',
         url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
   },
];
